### ISSUE TITLE
Javascript written in Hebrew

### ISSUE THREAD

**Issue by adamsr123** [reactjs/he.reactjs.org#145]
In the main page we may see:
![Captura de pantalla 2020-07-12 a las 14 51 48](https://user-images.githubusercontent.com/16638744/87245607-44907600-c44f-11ea-9a86-0b73e0916457.png)

I think that as Javascript being a world-reknowned programming language, the fifth line should write Javascript and not Javascript in Hebrew!

**Comment by galnir** [comment]
You're welcome to open a pull request and change that if it bothers you. I'd say it has to do more with the fact that most of the contributors wrote JavaScript in English, than JavaScript being a "world-reknowned" language.

**Comment by adamsr123** [comment]
@galnir 
True. I tried to open it but I receive 403 status when pushing. Maybe it's because a setting on the repository

**Comment by galnir** [comment]
Addressed in #147
