### ISSUE TITLE
Issue with the example code

### ISSUE THREAD

**Issue by ekurer** [reactjs/he.reactjs.org#272]
![Screen Shot 2022-06-07 at 14 14 33](https://user-images.githubusercontent.com/60178602/172366418-08725d09-f185-46d2-a04b-cef8a5583ef6.png)

**Comment by hannanel100** [comment]
@galnir, @galtalmor @itayyehezkel   i have opened a PR with a fix for this issue. is that ok?

**Comment by galnir** [comment]
> @galnir, @galtalmor @itayyehezkel i have opened a PR with a fix for this issue. is that ok?

Merged your PR, thank you!
